"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import subprocess

from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+yreio^zw-3xvz5ggnq9xq(@l&m-01npg42zci$%m%+aqa%455'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [

    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    # "unfold.contrib.location_field",  # optional, if django-location-field package is used
    # "unfold.contrib.constance",  # optional, if django-constance package is used
    "django.contrib.admin",  # required

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'equipments',
    'accounts',

    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    "corsheaders",
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

def get_latest_git_tag():
    try:
        tag = subprocess.check_output(
            ['git', 'describe', '--tags', '--abbrev=0'],
            cwd=BASE_DIR,
            stderr=subprocess.STDOUT
        ).decode().strip()
        return tag
    except Exception:
        return 'unknown'

SPECTACULAR_SETTINGS = {
    'TITLE': '803z-web-server',
    'DESCRIPTION': 'API documentation for 803Z project',
    'VERSION': get_latest_git_tag(),
    'SERVE_INCLUDE_SCHEMA': True,
}

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], 
        # 'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

# from django.templatetags.static import static
# from django.urls import reverse_lazy
# from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "803Z",
    "SITE_HEADER": "Administration 803Z",
    "SITE_SUBHEADER": "Pas touche !",
    "DASHBOARD_CALLBACK": "project.views.dashboard_callback",
    "SITE_DROPDOWN": [
        {
            "icon": "menu_book",
            "title": "Documentation API",
            "link": "/api/schema/redoc",
        },
        {
            "icon": "web",
            "title": "Web app (front-end)",
            "link": "http://localhost:3000",
        },
    ],
    "SITE_URL": "/",
    "SITE_SYMBOL": "database_search",  # symbol from icon set
    "SHOW_HISTORY": False, # show/hide "History" button, default: True
    "SHOW_VIEW_ON_SITE": False, # show/hide "View on site" button, default: True
    "SHOW_BACK_BUTTON": False, # show/hide "Back" button on changeform in header, default: False
    # "ENVIRONMENT": "development", # environment name in header
    # "ENVIRONMENT_TITLE_PREFIX": "sample_app.environment_title_prefix_callback", # environment name prefix in title tag
    # "DASHBOARD_CALLBACK": "sample_app.dashboard_callback",
    "THEME": "dark", # Force theme: "dark" or "light". Will disable theme switcher
    # "LOGIN": {
    #     "image": lambda request: static("sample/login-bg.jpg"),
    #     "redirect_after": lambda request: reverse_lazy("admin:APP_MODEL_changelist"),
    # },
    # "STYLES": [
    #     lambda request: static("css/style.css"),
    # ],
    # "SCRIPTS": [
    #     lambda request: static("js/script.js"),
    # ],
    # "BORDER_RADIUS": "0px",
    "COLORS": {
        "base": {
            "50": "#FFFFFF",
            "100": "oklch(96.7% 0.001 286.375)",
            "200": "oklch(92% 0.004 286.32)",
            "300": "oklch(87.1% 0.006 286.286)",
            "400": "oklch(70.5% 0.015 286.067)",
            "500": "oklch(55.2% 0.016 285.938)",
            "600": "oklch(44.2% 0.017 285.786)",
            "700": "oklch(37% 0.013 285.805)",
            "800": "oklch(27.4% 0.006 286.033)",
            "900": "oklch(21% 0.006 285.885)",
            "950": "oklch(14.1% 0.005 285.823)",
        },
        "primary": {
            "50": "#FFF3E0",
            "100": "#FFE0B2",
            "200": "#FFCC80",
            "300": "#FFB74D",
            "400": "#FFA726",
            "500": "#FF9800",
            "600": "#FB8C00",
            "700": "#F57C00",
            "800": "#EF6C00",
            "900": "#E65100",
            "950": "#E65100",
        },
        # "font": {
        #     "subtle-light": "var(--color-base-500)",  # text-base-500
        #     "subtle-dark": "var(--color-base-400)",  # text-base-400
        #     "default-light": "var(--color-base-600)",  # text-base-600
        #     "default-dark": "var(--color-base-300)",  # text-base-300
        #     "important-light": "var(--color-base-900)",  # text-base-900
        #     "important-dark": "var(--color-base-100)",  # text-base-100
        # },
    },
    # "EXTENSIONS": {
    #     "modeltranslation": {
    #         "flags": {
    #             "en": "🇬🇧",
    #             "fr": "🇫🇷",
    #             "nl": "🇧🇪",
    #         },
    #     },
    # },
    "SIDEBAR": {
        "show_search": True,  # Search in applications and models names
        # "command_search": True,  # Replace the sidebar search with the command search
        # "show_all_applications": True,  # Dropdown with all applications and models
        "navigation": [
            {
                "title": "General",
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Home",
                        "icon": "bar_chart",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:index"),
                        # "badge": "sample_app.badge_callback",
                        # "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
            {
                "title": "Accounts",
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        # "badge": "sample_app.badge_callback",
                        # "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": "Tokens",
                        "icon": "password",
                        "link": reverse_lazy("admin:authtoken_token_changelist"),
                    },
                ],
            },
            {
                "title": "Equipments",
                "separator": False,  # Top border
                "collapsible": False,  # Collapsible group of links
                "items": [
                    {
                        "title": "Categories",
                        "icon": "folder",  # Supported icon set: https://fonts.google.com/icons
                        "link": reverse_lazy("admin:equipments_category_changelist"),
                        # "badge": "sample_app.badge_callback",
                        # "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Subcategories",
                        "icon": "folder_open",
                        "link": reverse_lazy("admin:equipments_subcategory_changelist"),
                    },
                    {
                        "title": "Equipments",
                        "icon": "photo_camera",
                        "link": reverse_lazy("admin:equipments_equipment_changelist"),
                    },
                    {
                        "title": "Reservations",
                        "icon": "date_range",
                        "link": reverse_lazy("admin:equipments_reservation_changelist"),
                        "badge": "5",
                    },
                ],
            },
        ],
    },
    # "TABS": [
    #     # {
    #     #     "models": [
    #     #         "app_label.model_name_in_lowercase",
    #     #     ],
    #     #     "items": [
    #     #         {
    #     #             "title": _("Your custom title"),
    #     #             "link": reverse_lazy("admin:app_label_model_name_changelist"),
    #     #             # "permission": "sample_app.permission_callback",
    #     #         },
    #     #     ],
    #     # },
    # ],
}


# def dashboard_callback(request, context):
#     """
#     Callback to prepare custom variables for index template which is used as dashboard
#     template. It can be overridden in application by creating custom admin/index.html.
#     """
#     context.update(
#         {
#             "sample": "example",  # this will be injected into templates/admin/index.html
#         }
#     )
#     return context


# def environment_callback(request):
#     """
#     Callback has to return a list of two values represeting text value and the color
#     type of the label displayed in top right corner.
#     """
#     return ["Production", "danger"] # info, danger, warning, success


# def badge_callback(request):
#     return 3

# def permission_callback(request):
#     return request.user.has_perm("sample_app.change_model")