# Generated by Django 5.2.5 on 2025-08-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipmentcategory_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryGroup',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='EquipmentCategory',
            new_name='SubCategory',
        ),
    ]
