# Generated by Django 5.2.5 on 2025-08-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_rename_categorygroup_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='equipment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='equipment',
            field=models.ManyToManyField(related_name='reservations', to='equipments.equipment'),
        ),
    ]
