# Generated by Django 5.2.5 on 2025-08-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='group',
            new_name='category',
        ),
    ]
