# Generated by Django 5.2.5 on 2025-08-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='subcategories', to='equipments.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notes internes (visibles par le staff uniquement)'),
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='group',
        ),
    ]
