# Generated by Django 5.2.5 on 2025-08-17 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_subcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notes internes (visibles par le staff uniquement)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subcategories', to='equipments.category'),
        ),
    ]
