# Generated by Django 5.2.5 on 2025-08-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_alter_equipment_note_alter_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='equipment_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='equipments.equipment')),
            ],
        ),
    ]
